In [2]:
import numpy as np
import scipy as sp
%precision 3

'%.3f'

In [3]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [4]:
sp.sum(fish_data)

40

In [5]:
len(fish_data)

10

In [6]:
# 平均値
N = len(fish_data)
sum_value = sp.sum(fish_data)
mu = sum_value / N
mu

4.0

In [7]:
sp.mean(fish_data)

4.0

In [9]:
# 標本分散
sigma_2_sample = sp.sum((fish_data - mu) ** 2) / N
sigma_2_sample

1.2

In [11]:
sp.var(fish_data, ddof= 0)

1.2

In [12]:
# 不偏分散
sigma_2 = sp.sum((fish_data - mu) ** 2) / (N - 1)
sigma_2

1.3333333333333333

In [13]:
sp.var(fish_data, ddof=1)

1.3333333333333333

In [14]:
# 標準偏差
sigma = sp.sqrt(sigma_2)
sigma

1.1547005383792515

In [15]:
sp.std(fish_data, ddof=1)

1.1547005383792515

In [17]:
# 標準化 平均を0　標準偏差を1にする変換
# 平均を0にする方法
print(fish_data - mu)
sp.mean(fish_data - mu)

[-2. -1. -1.  0.  0.  0.  0.  1.  1.  2.]


0.0

In [18]:
# 標準偏差を1にする方法
print(fish_data / sigma)
sp.std(fish_data / sigma, ddof=1)


[1.732 2.598 2.598 3.464 3.464 3.464 3.464 4.33  4.33  5.196]


1.0

In [19]:
standart = (fish_data - mu) / sigma
standart

array([-1.732, -0.866, -0.866,  0.   ,  0.   ,  0.   ,  0.   ,  0.866,
        0.866,  1.732])

In [20]:
sp.mean(standart)

2.2204460492503132e-17

In [21]:
sp.std(standart, ddof = 1)

1.0

In [22]:
sp.amax(fish_data)

6

In [23]:
sp.amin(fish_data)

2

In [24]:
fish_data_2 = np.array([2,3,3,4,4,4,4,5,5,100])

In [25]:
# 平均値が大きい値に引きずられる
sp.mean(fish_data_2)

13.4

In [26]:
# 中央値は変化がない
sp.median(fish_data_2)

4.0

In [27]:
from scipy import stats

In [28]:
fish_data_3 = np.array([1,2,3,4,5,6,7,8,9])
stats.scoreatpercentile(fish_data_3, 25)

3.0

In [29]:
stats.scoreatpercentile(fish_data_3, 75)

7.0